
# .github/workflows/single-stage.yml

name: Single-Stage #Name of the workflow

on:
  push: #runs when a push to master happens
    branches: ['master']
  pull_request: #or when a pull from master is requested
    branches: ['master']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS #this action defines which version of node to install
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install node packages #We install the packages from the package manifest.
        run: npm install
      - name: install the linter
        run: npm install eslint
      - name: run the linter
        run: ./node_modules/.bin/eslint .
      #- name: run the linter #We run the linter using the script alias in the package manifest.
      #  run: npm run linter
